version: "3.8"

services:
  ytsync:
    # Use pre-built image from GitHub Container Registry (uncomment when using CI/CD)
    # image: ghcr.io/DmitriyLyalyuev/ytsync:latest

    # Or build locally (comment out when using pre-built image)
    build:
      context: .
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}

    container_name: youtube-sync
    restart: unless-stopped

    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./db:/app/db
      - ./downloads:/app/downloads

    environment:
      - TZ=Europe/Moscow
      - PYTHONUNBUFFERED=1
      - USER_UID=${USER_UID:-1000}
      - USER_GID=${USER_GID:-1000}
